### ISSUE TITLE
this doesnt work in Netlify buildbot yet

### ISSUE THREAD

**Issue by swyxio** [netlify-labs/netlify-plugin-a11y#2]
axe Cant find chrome.

![image](https://user-images.githubusercontent.com/6764957/76240418-93ac6d00-6209-11ea-9244-19b22d21ec97.png)

https://app.netlify.com/sites/netlify-plugin-axe-demo/deploys/5e6669eeed10eb2a27dac58f

```bash

12:10:12 PM: ┌────────────────────────────────────────────────────────┐
12:10:12 PM: │ 3. Running onPostBuild command from netlify-plugin-axe │
12:10:12 PM: └────────────────────────────────────────────────────────┘
12:10:12 PM: ​
12:10:12 PM: Running axe-core 3.5.1 in chrome-headless
12:10:12 PM: /opt/build/repo/node_modules/selenium-webdriver/lib/promise.js:2626
12:10:12 PM:         throw error;
12:10:12 PM:         ^
12:10:12 PM: WebDriverError: unknown error: cannot find Chrome binary
12:10:12 PM:   (Driver info: chromedriver=80.0.3987.16 (320f6526c1632ad4f205ebce69b99a062ed78647-refs/branch-heads/3987@{#185}),platform=Linux 4.14.65+ x86_64)
12:10:12 PM:     at Object.checkLegacyResponse (/opt/build/repo/node_modules/selenium-webdriver/lib/error.js:546:15)
12:10:12 PM:     at parseHttpResponse (/opt/build/repo/node_modules/selenium-webdriver/lib/http.js:509:13)
12:10:12 PM:     at doSend.then.response (/opt/build/repo/node_modules/selenium-webdriver/lib/http.js:441:30)
12:10:12 PM:     at process._tickCallback (internal/process/next_tick.js:68:7)
12:10:12 PM: From: Task: WebDriver.createSession()
12:10:12 PM:     at Function.createSession (/opt/build/repo/node_modules/selenium-webdriver/lib/webdriver.js:769:24)
12:10:12 PM:     at Function.createSession (/opt/build/repo/node_modules/selenium-webdriver/chrome.js:761:15)
12:10:12 PM:     at createDriver (/opt/build/repo/node_modules/selenium-webdriver/index.js:170:33)
12:10:12 PM:     at Builder.build (/opt/build/repo/node_modules/selenium-webdriver/index.js:642:16)
12:10:12 PM:     at startDriver (/opt/build/repo/node_modules/axe-cli/lib/webdriver.js:37:26)
12:10:12 PM:     at testPages (/opt/build/repo/node_modules/axe-cli/lib/axe-test-urls.js:11:10)
12:10:12 PM:     at Object.<anonymous> (/opt/build/repo/node_modules/axe-cli/index.js:136:1)
12:10:12 PM:     at Module._compile (internal/modules/cjs/loader.js:778:30)
12:10:12 PM:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
12:10:12 PM:     at Module.load (internal/modules/cjs/loader.js:653:32)
12:10:12 PM: ​
12:10:12 PM: ┌─────────────────────────────┐
12:10:12 PM: │    Plugin internal error    │
```

netlify internal slack convo https://netlify.slack.com/archives/CPCL7QAE4/p1583769753103600?thread_ts=1583436966.076500&cid=CPCL7QAE4

## Things I tried

- https://github.com/jaimeiniesta/serverless-axe-cli/pull/1
- https://github.com/adieuadieu/serverless-chrome/issues/143
- https://gist.github.com/stephenmathieson/57c1fa4a8a6bdbb489f91d4a4f713ee9
- npm install chromedriver
  - https://github.com/SeleniumHQ/selenium/issues/4863
  - https://www.selenium.dev/documentation/en/webdriver/driver_requirements/
- https://github.com/dequelabs/axe-cli/issues/84

**Comment by swyxio** [comment]
things to try - axe chromedriver path https://github.com/dequelabs/axe-cli/#chromedriver-path

pa11y chromeConfig - https://github.com/pa11y/pa11y#chromelaunchconfig-object

https://css-tricks.com/accessibility-testing-tools/

**Comment by swyxio** [comment]
i think i will drop axe. i dont know


https://app.netlify.com/sites/netlify-plugin-axe-demo/deploys/5e726df6a63dc300083d7f8d

```bash
2:53:32 PM: { chromePath:
2:53:32 PM:    '/opt/build/repo/node_modules/lib/chromedriver/chromedriver_mac64.zip' }
2:53:32 PM: Running axe-core 3.5.1 in chrome-headless
2:53:32 PM: /opt/build/repo/node_modules/selenium-webdriver/remote/index.js:330
2:53:32 PM:       throw Error(`The specified executable path does not exist: ${exe}`);
2:53:32 PM:       ^
2:53:32 PM: Error: The specified executable path does not exist: "/opt/build/repo/node_modules/lib/chromedriver/chromedriver_mac64.zip"
2:53:32 PM:     at new DriverService.Builder (/opt/build/repo/node_modules/selenium-webdriver/remote/index.js:330:13)
2:53:32 PM:     at new ServiceBuilder (/opt/build/repo/node_modules/selenium-webdriver/chrome.js:222:5)
2:53:32 PM:     at startDriver (/opt/build/repo/node_modules/axe-cli/lib/webdriver.js:16:19)
2:53:32 PM:     at testPages (/opt/build/repo/node_modules/axe-cli/lib/axe-test-urls.js:11:10)
2:53:32 PM:     at Object.<anonymous> (/opt/build/repo/node_modules/axe-cli/index.js:136:1)
2:53:32 PM:     at Module._compile (internal/modules/cjs/loader.js:778:30)
2:53:32 PM:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
2:53:32 PM:     at Module.load (internal/modules/cjs/loader.js:653:32)
2:53:32 PM:     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
2:53:32 PM:     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
2:53:32 PM: ​
```

**Comment by swyxio** [comment]
solved! 
![image](https://user-images.githubusercontent.com/6764957/77146484-868d4a80-6a61-11ea-84cc-703c2abd6d6e.png)


![image](https://user-images.githubusercontent.com/6764957/77147207-226b8600-6a63-11ea-91b2-2de449ef6682.png)

**Comment by swyxio** [comment]
![image](https://user-images.githubusercontent.com/6764957/77147811-8b073280-6a64-11ea-834d-6b872e543e23.png)
